language: python

python:
- '3.6'

notifications:
  on_success: never
  on_failure: never

install:
- pip install django

script:
- python3 exit0.py

after_success:
- openssl aes-256-cbc -K $encrypted_e610fedd3ccc_key -iv $encrypted_e610fedd3ccc_iv
  -in deploy_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- ./deploy.sh
- rm ~/.ssh/id_rsa
