# Generated by Django 2.0.5 on 2018-05-31 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.CharField(max_length=200)),
                ('house_id', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HouseReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_in_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('pros', models.TextField()),
                ('cons', models.TextField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('house_filed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.House')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='reports',
            field=models.ManyToManyField(blank=True, to='reviews.HouseReport'),
        ),
    ]
