# Generated by Django 2.0.5 on 2018-05-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='house_id',
        ),
        migrations.RemoveField(
            model_name='house',
            name='reports',
        ),
    ]
